[package]
name = "verify_token_with_some_key"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^2.3.0", default-features = false, features = ['std'] }
jwt-core = { path = "../../core/" }