[package]
name = "jwt-core"
version = "0.1.1"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jwt-compact = { version = "0.8", features = ["rsa"] }
serde = "1.0.228"
serde_json = "1.0.149"
thiserror = "1.0.69"
